// var nodes = ['MIL','LAM','ROM','VEN','NAP','FIO','SIR'];//'PAL''SIR'
var nodes = ['LAM','ROM','VEN','NAP','FIO','CAT'];//'PAL''SIR'
var edges = [
        {source:'BCN', destination:'MIL', weight:68},
        {source:'BCN', destination:'LAM', weight:182},    
        {source:'BCN', destination:'NAP', weight:85},
        {source:'BCN', destination:'VEN', weight:101},
        {source:'BCN', destination:'FIO', weight:75},
        {source:'BCN', destination:'ROM', weight:70},
        {source:'BCN', destination:'CAT', weight:125},
        {source:'BCN', destination:'PAL', weight:135},
        {source:'BCN', destination:'SIR', weight:125},
        {source:'MIL', destination:'LAM', weight:30},
        {source:'MIL', destination:'NAP', weight:20},
        {source:'MIL', destination:'VEN', weight:10},
        {source:'MIL', destination:'FIO', weight:14},
        {source:'MIL', destination:'ROM', weight:16},
        {source:'MIL', destination:'BCN', weight:33},
        {source:'LAM', destination:'MIL', weight:98},
        {source:'LAM', destination:'NAP', weight:10},
        {source:'LAM', destination:'VEN', weight:69},
        {source:'LAM', destination:'FIO', weight:58},
        {source:'LAM', destination:'ROM', weight:20},
        {source:'LAM', destination:'BCN', weight:184},
        {source:'SIR', destination:'LAM', weight:99999},//NO HAY
        {source:'SIR', destination:'MIL', weight:98},
        {source:'SIR', destination:'NAP', weight:49},
        {source:'SIR', destination:'VEN', weight:86},
        {source:'SIR', destination:'FIO', weight:72},
        {source:'SIR', destination:'ROM', weight:49},
        {source:'SIR', destination:'BCN', weight:135},
        {source:'PAL', destination:'LAM', weight:32},
        {source:'PAL', destination:'MIL', weight:91},
        {source:'PAL', destination:'NAP', weight:56},
        {source:'PAL', destination:'VEN', weight:92},
        {source:'PAL', destination:'FIO', weight:68},
        {source:'PAL', destination:'ROM', weight:60},
        {source:'PAL', destination:'BCN', weight:145},
        {source:'CAT', destination:'LAM', weight:26},
        {source:'CAT', destination:'MIL', weight:98},
        {source:'CAT', destination:'NAP', weight:60},
        {source:'CAT', destination:'VEN', weight:76},
        {source:'CAT', destination:'FIO', weight:89},
        {source:'CAT', destination:'ROM', weight:49},
        {source:'CAT', destination:'BCN', weight:135},
        {source:'NAP', destination:'LAM', weight:13},
        {source:'NAP', destination:'VEN', weight:56},
        {source:'NAP', destination:'FIO', weight:30},
        {source:'NAP', destination:'ROM', weight:7},
        {source:'NAP', destination:'BCN', weight:45},
        {source:'NAP', destination:'MIL', weight:20},
        {source:'VEN', destination:'LAM', weight:75},
        {source:'VEN', destination:'NAP', weight:56},
        {source:'VEN', destination:'FIO', weight:20},
        {source:'VEN', destination:'ROM', weight:28},
        {source:'VEN', destination:'BCN', weight:55},
        {source:'VEN', destination:'MIL', weight:10},
        {source:'FIO', destination:'LAM', weight:24},
        {source:'FIO', destination:'NAP', weight:40},
        {source:'FIO', destination:'VEN', weight:14},
        {source:'FIO', destination:'ROM', weight:10},
        {source:'FIO', destination:'BCN', weight:28},
        {source:'FIO', destination:'MIL', weight:10},
        {source:'ROM', destination:'LAM', weight:13},
        {source:'ROM', destination:'NAP', weight:7},
        {source:'ROM', destination:'VEN', weight:43},
        {source:'ROM', destination:'FIO', weight:10},
        {source:'ROM', destination:'BCN', weight:50},
        {source:'ROM', destination:'MIL', weight:40},
        {source:'MIL', destination:'CAT', weight:25},
        {source:'MIL', destination:'PAL', weight:30},
        {source:'MIL', destination:'SIR', weight:25},
        {source:'LAM', destination:'CAT', weight:16},
        {source:'LAM', destination:'PAL', weight:13},
        {source:'LAM', destination:'SIR', weight:9999},//NO HAY FORMA
        {source:'NAP', destination:'CAT', weight:46},
        {source:'NAP', destination:'PAL', weight:56},
        {source:'NAP', destination:'SIR', weight:46},
        {source:'VEN', destination:'PAL', weight:30},
        {source:'VEN', destination:'SIR', weight:40},
        {source:'VEN', destination:'CAT', weight:50},
        {source:'FIO', destination:'PAL', weight:26},
        {source:'FIO', destination:'SIR', weight:33},
        {source:'FIO', destination:'CAT', weight:33},
        {source:'ROM', destination:'PAL', weight:35},
        {source:'ROM', destination:'SIR', weight:24},
        {source:'ROM', destination:'CAT', weight:24}]; 

module.exports = {
    nodes: function(){
        return nodes;
    },
    edges: function(){
        return edges;
    }
}
//CHEAPEST: BCN - VEN - MIL -ROM - BCN