// var nodes = ['MIL','LAM','ROM','VEN','NAP','FIO','CAT'];//'PAL''SIR'
var nodes = ['LAM','ROM','VEN','NAP','FIO','PAL'];//'PAL''SIR'
var edges = [
        {source:'BCN', destination:'MIL', weight:80, conveyance: 'plane', operator: 'Vueling', duration:95},
        {source:'BCN', destination:'LAM', weight:183, conveyance: 'plane', operator: 'Alitalia', duration:290},    
        {source:'BCN', destination:'NAP', weight:87, conveyance: 'plane', operator: 'Ryanair', duration:115},
        {source:'BCN', destination:'VEN', weight:101, conveyance: 'plane', operator: 'Ryanair', duration:120},
        {source:'BCN', destination:'FIO', weight:115, conveyance: 'plane', operator: 'Vueling', duration:105},
        {source:'BCN', destination:'ROM', weight:80, conveyance: 'plane', operator: 'Vueling', duration:110},
        {source:'BCN', destination:'CAT', weight:167, conveyance: 'plane', operator: 'Alitalia', duration:250},
        {source:'BCN', destination:'PAL', weight:135, conveyance: 'plane', operator: 'Vueling', duration:305},
        {source:'BCN', destination:'SIR', weight:999999, conveyance: 'plane', operator: 'Vueling', duration:125},//no dan los horarios
        {source:'MIL', destination:'LAM', weight:30, conveyance: 'plane', operator: 'Ryanair', duration:105},
        {source:'MIL', destination:'NAP', weight:20, conveyance: 'plane', operator: 'Ryanair', duration:85},
        {source:'MIL', destination:'VEN', weight:10, conveyance: 'bus', operator: 'BusCenter', duration:245},
        {source:'MIL', destination:'FIO', weight:14, conveyance: 'bus', operator: 'Flixbus', duration:270},
        {source:'MIL', destination:'ROM', weight:36, conveyance: 'plane', operator: 'Alitalia', duration:70},
        {source:'MIL', destination:'BCN', weight:33, conveyance: 'plane', operator: 'Ryanair', duration:104},
        {source:'LAM', destination:'MIL', weight:95, conveyance: 'plane', operator: 'Alitalia', duration:95},
        {source:'LAM', destination:'NAP', weight:20, conveyance: 'train', operator: 'Trenitalia', duration:183},
        {source:'LAM', destination:'VEN', weight:69, conveyance: 'plane', operator: 'Alitalia', duration:305},
        {source:'LAM', destination:'FIO', weight:59, conveyance: 'plane', operator: 'Ryanair', duration:95},
        {source:'LAM', destination:'ROM', weight:46, conveyance: 'plane', operator: 'Alitalia', duration:70},
        {source:'LAM', destination:'BCN', weight:185, conveyance: 'plane', operator: 'Alitalia', duration:260},
        {source:'SIR', destination:'LAM', weight:99999, conveyance: '', operator: ''},//NO HAY
        {source:'SIR', destination:'MIL', weight:98, conveyance: 'plane', operator: 'Ryanair', duration:115},
        {source:'SIR', destination:'NAP', weight:48, conveyance: 'plane', operator: 'Alitalia', duration:75},
        {source:'SIR', destination:'VEN', weight:56, conveyance: 'plane', operator: 'Volotea', duration:110},
        {source:'SIR', destination:'FIO', weight:30, conveyance: 'plane', operator: 'Ryanair', duration:95},
        {source:'SIR', destination:'ROM', weight:52, conveyance: 'plane', operator: 'Alitalia', duration:85},
        {source:'SIR', destination:'BCN', weight:135, conveyance: 'plane', operator: 'Vueling', duration:135},
        {source:'PAL', destination:'LAM', weight:13, conveyance: 'train', operator: 'Trenitalia', duration:357},
        {source:'PAL', destination:'MIL', weight:112, conveyance: 'plane', operator: 'Alitalia', duration:95},
        {source:'PAL', destination:'NAP', weight:24, conveyance: 'plane', operator: 'Volotea', duration:60},
        {source:'PAL', destination:'VEN', weight:76, conveyance: 'plane', operator: 'Ryanair', duration:100},
        {source:'PAL', destination:'FIO', weight:38, conveyance: 'plane', operator: 'Ryanair', duration:85},
        {source:'PAL', destination:'ROM', weight:59, conveyance: 'plane', operator: 'Alitalia', duration:70},
        {source:'PAL', destination:'BCN', weight:145, conveyance: 'plane', operator: 'Alitalia', duration:120},
        {source:'CAT', destination:'LAM', weight:13, conveyance: 'train', operator: 'Trenitalia', duration:256},
        {source:'CAT', destination:'MIL', weight:98, conveyance: 'plane', operator: 'Ryanair', duration:115},
        {source:'CAT', destination:'NAP', weight:48, conveyance: 'plane', operator: 'Alitalia', duration:75},
        {source:'CAT', destination:'VEN', weight:56, conveyance: 'plane', operator: 'Volotea', duration:110},
        {source:'CAT', destination:'FIO', weight:36, conveyance: 'plane', operator: 'Ryanair', duration:95},
        {source:'CAT', destination:'ROM', weight:52, conveyance: 'plane', operator: 'Alitalia', duration:85},
        {source:'CAT', destination:'BCN', weight:135, conveyance: 'plane', operator: 'Vueling', duration:135},
        {source:'NAP', destination:'LAM', weight:10, conveyance: 'train', operator: 'Trenitalia', duration:177},
        {source:'NAP', destination:'VEN', weight:26, conveyance: 'plane', operator: 'Volotea', duration:80},
        {source:'NAP', destination:'FIO', weight:30, conveyance: 'train', operator: 'Trenitalia', duration:171},
        {source:'NAP', destination:'ROM', weight:7, conveyance: 'bus', operator: 'Flixbus', duration:155},
        {source:'NAP', destination:'BCN', weight:45, conveyance: 'plane', operator: 'Vueling', duration:119},
        {source:'NAP', destination:'MIL', weight:20, conveyance: 'plane', operator: 'Ryanair', duration:85},
        {source:'VEN', destination:'LAM', weight:75, conveyance: 'plane', operator: 'Alitalia', duration:220},
        {source:'VEN', destination:'NAP', weight:15, conveyance: 'plane', operator: 'Volotea', duration:80},
        {source:'VEN', destination:'FIO', weight:20, conveyance: 'train', operator: 'Trenitalia', duration:125},
        {source:'VEN', destination:'ROM', weight:52, conveyance: 'plane', operator: 'Alitalia', duration:60},
        {source:'VEN', destination:'BCN', weight:55, conveyance: 'plane', operator: 'Vueling', duration:115},
        {source:'VEN', destination:'MIL', weight:10, conveyance: 'train', operator: 'Trenitalia', duration:155},
        {source:'FIO', destination:'LAM', weight:20, conveyance: 'plane', operator: 'Ryanair', duration:95},
        {source:'FIO', destination:'NAP', weight:20, conveyance: 'bus', operator: 'BusCenter', duration:340},
        {source:'FIO', destination:'VEN', weight:20, conveyance: 'train', operator: 'Trenitalia', duration:113},
        {source:'FIO', destination:'ROM', weight:10, conveyance: 'train', operator: 'Trenitalia', duration:77},
        {source:'FIO', destination:'BCN', weight:34, conveyance: 'plane', operator: 'Ryanair', duration:105},
        {source:'FIO', destination:'MIL', weight:10, conveyance: 'bus', operator: 'Flixbus', duration:270},
        {source:'ROM', destination:'LAM', weight:20, conveyance: 'train', operator: 'Trenitalia', duration:292},
        {source:'ROM', destination:'NAP', weight:7, conveyance: 'bus', operator: 'Flixbus', duration:275},
        {source:'ROM', destination:'VEN', weight:45, conveyance: 'plane', operator: 'Alitalia', duration:70},
        {source:'ROM', destination:'FIO', weight:10, conveyance: 'train', operator: 'Trenitalia', duration:91},
        {source:'ROM', destination:'BCN', weight:42, conveyance: 'plane', operator: 'Ryanair', duration:115},
        {source:'ROM', destination:'MIL', weight:40, conveyance: 'train', operator: 'Trenitalia', duration:182},
        {source:'MIL', destination:'CAT', weight:24, conveyance: 'plane', operator: 'Ryanair', duration:115},
        {source:'MIL', destination:'PAL', weight:29, conveyance: 'plane', operator: 'Ryanair', duration:105},
        {source:'MIL', destination:'SIR', weight:25, conveyance: 'plane', operator: 'Ryanair', duration:115},
        {source:'LAM', destination:'CAT', weight:16, conveyance: 'train', operator: 'Trenitalia', duration:134},
        {source:'LAM', destination:'PAL', weight:21, conveyance: 'train', operator: 'Trenitalia', duration:345},
        {source:'LAM', destination:'SIR', weight:9999, conveyance: '', operator: ''},//NO HAY FORMA
        {source:'NAP', destination:'CAT', weight:47, conveyance: 'plane', operator: 'Easyjet', duration:60},
        {source:'NAP', destination:'PAL', weight:26, conveyance: 'plane', operator: 'Volotea', duration:60},
        {source:'NAP', destination:'SIR', weight:47, conveyance: 'plane', operator: 'Easyjet', duration:60},
        {source:'VEN', destination:'PAL', weight:44, conveyance: 'plane', operator: 'Ryanair', duration:95},
        {source:'VEN', destination:'SIR', weight:44, conveyance: 'plane', operator: 'Volotea', duration:105},
        {source:'VEN', destination:'CAT', weight:44, conveyance: 'plane', operator: 'Volotea', duration:105},
        {source:'FIO', destination:'PAL', weight:26, conveyance: 'plane', operator: 'Ryanair', duration:85},
        {source:'FIO', destination:'SIR', weight:33, conveyance: 'plane', operator: 'Ryanair', duration:90},
        {source:'FIO', destination:'CAT', weight:36, conveyance: 'plane', operator: 'Ryanair', duration:90},
        {source:'ROM', destination:'PAL', weight:35, conveyance: 'plane', operator: 'Alitalia', duration:70},
        {source:'ROM', destination:'SIR', weight:35, conveyance: 'plane', operator: 'Alitalia', duration:75},
        {source:'ROM', destination:'CAT', weight:35, conveyance: 'plane', operator: 'Alitalia', duration:115}]; 

module.exports = {
    nodes: function(){
        return nodes;
    },
    edges: function(){
        return edges;
    }
}